"""rpg_world_system

Revision ID: 35591c12dc29
Revises: 002
Create Date: 2026-01-05 23:06:52.420578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '35591c12dc29'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enemy_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_speed', sa.Integer(), nullable=False),
    sa.Column('crit_chance', sa.Float(), nullable=False),
    sa.Column('aggro_range', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('coin_reward', sa.Integer(), nullable=False),
    sa.Column('loot_table', sa.JSON(), nullable=False),
    sa.Column('movement_pattern', sa.String(length=50), nullable=False),
    sa.Column('is_boss', sa.Integer(), nullable=False),
    sa.Column('sprite_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enemies_enemy_type'), 'enemies', ['enemy_type'], unique=True)
    op.create_index(op.f('ix_enemies_id'), 'enemies', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('max_stack', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('attack_bonus', sa.Integer(), nullable=False),
    sa.Column('defense_bonus', sa.Integer(), nullable=False),
    sa.Column('hp_bonus', sa.Integer(), nullable=False),
    sa.Column('crit_bonus', sa.Float(), nullable=False),
    sa.Column('equip_slot', sa.String(length=50), nullable=True),
    sa.Column('weapon_type', sa.String(length=50), nullable=True),
    sa.Column('weapon_range', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=50), nullable=True),
    sa.Column('effect_value', sa.Integer(), nullable=False),
    sa.Column('effect_duration', sa.Integer(), nullable=False),
    sa.Column('sprite_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=True)
    op.create_table('world_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('terrain_data', sa.JSON(), nullable=False),
    sa.Column('spawn_x', sa.Integer(), nullable=False),
    sa.Column('spawn_y', sa.Integer(), nullable=False),
    sa.Column('connections', sa.JSON(), nullable=False),
    sa.Column('is_starting_zone', sa.Boolean(), nullable=False),
    sa.Column('level_requirement', sa.Integer(), nullable=False),
    sa.Column('enemy_level_min', sa.Integer(), nullable=False),
    sa.Column('enemy_level_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_zones_id'), 'world_zones', ['id'], unique=False)
    op.create_index(op.f('ix_world_zones_slug'), 'world_zones', ['slug'], unique=True)
    op.create_table('enemy_spawns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('enemy_id', sa.Integer(), nullable=False),
    sa.Column('spawn_x', sa.Integer(), nullable=False),
    sa.Column('spawn_y', sa.Integer(), nullable=False),
    sa.Column('level_min', sa.Integer(), nullable=False),
    sa.Column('level_max', sa.Integer(), nullable=False),
    sa.Column('respawn_time', sa.Integer(), nullable=False),
    sa.Column('is_boss', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enemy_id'], ['enemies.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['world_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enemy_spawns_id'), 'enemy_spawns', ['id'], unique=False)
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('npc_type', sa.String(length=50), nullable=False),
    sa.Column('dialogue_tree', sa.JSON(), nullable=False),
    sa.Column('is_shopkeeper', sa.Boolean(), nullable=False),
    sa.Column('shop_items', sa.JSON(), nullable=False),
    sa.Column('sprite_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['world_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_id'), 'npcs', ['id'], unique=False)
    op.create_index(op.f('ix_npcs_npc_id'), 'npcs', ['npc_id'], unique=True)
    op.create_table('world_chests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chest_id', sa.String(length=100), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('chest_type', sa.String(length=50), nullable=False),
    sa.Column('loot_table', sa.JSON(), nullable=False),
    sa.Column('coin_amount', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('required_key_item_id', sa.String(length=100), nullable=True),
    sa.Column('is_one_time', sa.Boolean(), nullable=False),
    sa.Column('respawn_time', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['world_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_chests_chest_id'), 'world_chests', ['chest_id'], unique=True)
    op.create_index(op.f('ix_world_chests_id'), 'world_chests', ['id'], unique=False)
    op.create_table('chest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chest_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chest_id'], ['world_chests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chest_id', name='uq_user_chest')
    )
    op.create_index(op.f('ix_chest_progress_id'), 'chest_progress', ['id'], unique=False)
    op.create_index(op.f('ix_chest_progress_user_id'), 'chest_progress', ['user_id'], unique=False)
    op.create_table('player_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('equip_slot', sa.Integer(), nullable=True),
    sa.Column('slot_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item')
    )
    op.create_index(op.f('ix_player_inventory_id'), 'player_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_player_inventory_user_id'), 'player_inventory', ['user_id'], unique=False)
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_index(op.f('ix_quests_slug'), table_name='quests')
    op.drop_table('quests')
    op.drop_index(op.f('ix_quest_progress_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_quest_id'), table_name='quest_progress')
    op.drop_index(op.f('ix_quest_progress_user_id'), table_name='quest_progress')
    op.drop_table('quest_progress')
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('characters') as batch_op:
        batch_op.drop_index(op.f('ix_characters_name'))
        batch_op.create_unique_constraint('uq_characters_name', ['name'])

    # Add columns to users with default values for SQLite
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('max_hp', sa.Integer(), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('mp', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('max_mp', sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('attack', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('defense', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('crit_chance', sa.Float(), nullable=False, server_default='0.05'))
        batch_op.add_column(sa.Column('current_zone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('world_x', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('world_y', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('equipped_weapon_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_head_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_chest_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_legs_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_feet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipped_accessory_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'equipped_accessory_id')
    op.drop_column('users', 'equipped_feet_id')
    op.drop_column('users', 'equipped_legs_id')
    op.drop_column('users', 'equipped_chest_id')
    op.drop_column('users', 'equipped_head_id')
    op.drop_column('users', 'equipped_weapon_id')
    op.drop_column('users', 'world_y')
    op.drop_column('users', 'world_x')
    op.drop_column('users', 'current_zone_id')
    op.drop_column('users', 'crit_chance')
    op.drop_column('users', 'speed')
    op.drop_column('users', 'defense')
    op.drop_column('users', 'attack')
    op.drop_column('users', 'max_mp')
    op.drop_column('users', 'mp')
    op.drop_column('users', 'max_hp')
    op.drop_column('users', 'hp')
    op.drop_constraint(None, 'characters', type_='unique')
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=1)
    op.create_table('quest_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quest_id', sa.INTEGER(), nullable=False),
    sa.Column('stars_earned', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('best_action_count', sa.INTEGER(), nullable=True),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest_id')
    )
    op.create_index(op.f('ix_quest_progress_user_id'), 'quest_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_quest_id'), 'quest_progress', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_progress_id'), 'quest_progress', ['id'], unique=False)
    op.create_table('quests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), server_default=sa.text('(50)'), nullable=False),
    sa.Column('coin_reward', sa.INTEGER(), server_default=sa.text('(10)'), nullable=False),
    sa.Column('node_x', sa.INTEGER(), nullable=False),
    sa.Column('node_y', sa.INTEGER(), nullable=False),
    sa.Column('level_requirement', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('prerequisite_quests', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('level_id', sa.INTEGER(), nullable=True),
    sa.Column('star_thresholds', sqlite.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quests_slug'), 'quests', ['slug'], unique=1)
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.drop_index(op.f('ix_player_inventory_user_id'), table_name='player_inventory')
    op.drop_index(op.f('ix_player_inventory_id'), table_name='player_inventory')
    op.drop_table('player_inventory')
    op.drop_index(op.f('ix_chest_progress_user_id'), table_name='chest_progress')
    op.drop_index(op.f('ix_chest_progress_id'), table_name='chest_progress')
    op.drop_table('chest_progress')
    op.drop_index(op.f('ix_world_chests_id'), table_name='world_chests')
    op.drop_index(op.f('ix_world_chests_chest_id'), table_name='world_chests')
    op.drop_table('world_chests')
    op.drop_index(op.f('ix_npcs_npc_id'), table_name='npcs')
    op.drop_index(op.f('ix_npcs_id'), table_name='npcs')
    op.drop_table('npcs')
    op.drop_index(op.f('ix_enemy_spawns_id'), table_name='enemy_spawns')
    op.drop_table('enemy_spawns')
    op.drop_index(op.f('ix_world_zones_slug'), table_name='world_zones')
    op.drop_index(op.f('ix_world_zones_id'), table_name='world_zones')
    op.drop_table('world_zones')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_enemies_id'), table_name='enemies')
    op.drop_index(op.f('ix_enemies_enemy_type'), table_name='enemies')
    op.drop_table('enemies')
    # ### end Alembic commands ###
